---
- name: Install NFS client package
  package:
    name: nfs-utils
    state: present

- name: Ensure NFS mount point exists
  file:
    path: "{{ nfs_mount_point }}"
    state: directory
    mode: '0755'

- name: Mount NFS share
  community.general.mount:
    path: "{{ nfs_mount_point }}"
    src: "{{ nfs_server }}:{{ nfs_export_path }}"
    fstype: nfs
    opts: "rw,soft,intr"

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ nfs_server }}:{{ nfs_export_path }} {{ nfs_mount_point }} nfs rw,soft,intr 0 0"
    create: yes

