version: '3.7'

services:
  control-plane:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == control-plane
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword

  node1:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --bind_ip_all
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword

  node2:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --bind_ip_all
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
      restart_policy:
        condition: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword

networks:
  mongo:
    driver: overlay

