version: '3.6'

services:
  mongo_main:
    image: mongo:4.4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - /data/control-plane/mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == control-plane

  mongo_replica1:
    image: mongo:4.4.0
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - /data/node1/mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1

  mongo_replica2:
    image: mongo:4.4.0
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - /data/node2/mongo:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2

volumes:
  mongo_data_main:
  mongo_data_replica1:
  mongo_data_replica2:
 
