version: '3.6'services:
  mongo1:
    image: mongo:4.0.0
    ports:
      - 7011:7011
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - /data/disk1/mongo1/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 1
    networks:
      - mongo
  mongo2:
    image: mongo:4.0.0
    ports:
      - 7012:7012
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - /data/disk1/mongo1/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
      constraints:
        - node.labels.mongo.replica == 1
    networks:
      - mongo
  mongo3:
    image: mongo:4.0.0
    ports:
      - 7013:7013
    environment:
      MONGO_INITDB_ROOT_USERNAME: ans_mariusz
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - /data/disk1/mongo1/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
      constraints:
        - node.labels.mongo.replica == 1
    networks:
      - mongo
  mongo4:
    image: mongo:4.0.0
    ports:
      - 7014:7014
    volumes:
      - /data/disk1/mongo1/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
      constraints:
        - node.labels.mongo.replica == 1
    networks:
      - mongo
