version: '3.6'

services:
  control-plane:
    image: mongo:4.0.0
    # command: mongod --replSet replicaTest --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == control-plane
      restart_policy:
        condition: on-failure

  node1:
    image: mongo:4.0.0
    # command: mongod --replSet replicaTest --port 27018 --bind_ip_all
    ports: 
      - "27018:27018"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
      restart_policy:
        condition: on-failure

  node2:
    image: mongo:4.0.0
    # command: mongod --replSet replicaTest --port 27019 --bind_ip_all
    ports: 
      - "27019:27019"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
      restart_policy:
        condition: on-failure

networks:
  mongo:
    driver: overlay

