version: '3.6'

services:
  control-plane:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == control-plane
      restart_policy:
        condition: on-failure

  node1:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --port 27018 --bind_ip_all
    ports: 
      - "27018:27018"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node1
      restart_policy:
        condition: on-failure

  node2:
    image: mongo:4.0.0
    command: mongod --replSet replicaTest --port 27019 --bind_ip_all
    ports: 
      - "27019:27019"
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node2
      restart_policy:
        condition: on-failure
  web:
    image: my-fedora-nginx
    ports:
      - "80:80"
    networks:
      - mongo
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - mongo1
      - mongo2
      - mongo3

networks:
  mongo:
    driver: overlay

