---
#### Ansible Roles
- name: Install Ansible roles
  command: ansible-galaxy collection install "{{ item }}"
  loop: "{{ roles_to_install }}"
  when: roles_to_install is defined

- name: Copy repository configuration files
  copy: 
    src: "{{ repo_files_source }}/{{ item }}.repo"
    dest: "/etc/yum.repos.d/{{ item }}.repo"
  loop: "{{ repos_to_enable }}"

#### PACKAGES ####
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    allowerasing: true
  loop: "{{ required_packages }}"
  when: "required_packages is defined"

#### SERVICES ####
- name: Enable required services now and on boot
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  loop: "{{ required_services }}"
  when: "required_services is defined"

### FIREWALL ###
- name: Firewalld - Dodanie serwisów z listy
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ firewall_services }}" 
  when: "firewall_services is defined"
  
- name: Firewalld - Dodanie portow tcp z listy
  ansible.posix.firewalld:
    port:  "{{ item}}/tcp"
    permanent: true
    state: enabled
  loop: "{{ firewall_tcp_ports }}" 
  when: "firewall_tcp_ports is defined"

- name: Firewalld - Przeladowanie uslugi
  command: firewall-cmd --reload