---
#### Ansible Roles
- name: Install Ansible roles
  command: ansible-galaxy collection install "{{ item }}"
  loop: "{{ roles_to_install }}"
  when: roles_to_install is defined

- name: Copy repository configuration files
  copy: 
    src: "{{ repo_files_source }}/{{ item }}.repo"
    dest: "/etc/yum.repos.d/{{ item }}.repo"
  loop: "{{ repos_to_enable }}"

#### PACKAGES ####
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    allowerasing: true
  loop: "{{ required_packages }}"
  when: "required_packages is defined"

#### SERVICES ####
- name: Enable required services now and on boot
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  loop: "{{ required_services }}"
  when: "required_services is defined"

### FIREWALL ###
- name: Firewalld - Dodanie serwisów z listy
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ firewall_services }}" 
  when: "firewall_services is defined"
  notify: "reload firewall"
  
- name: Firewalld - Dodanie portow tcp z listy
  ansible.posix.firewalld:
    port:  "{{ item}}/tcp"
    permanent: true
    state: enabled
  loop: "{{ firewall_tcp_ports }}" 
  when: "firewall_tcp_ports is defined"
  notify: "reload firewall"

- name: Firewalld - Dodanie portow tcp z listy
  ansible.posix.firewalld:
    port:  "{{ item}}/udp"
    permanent: true
    state: enabled
  loop: "{{ firewall_udp_ports }}" 
  when: "firewall_tcp_ports is defined"
  notify: "reload firewall"




### SELINUX ###
# - name: SELinux - wylaczenie tymczasowe
  # command: setenforce 0

# - name: SELinux - wylaczenie trwale
  # command: "sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux"

### Ip-tables bridge? 
# - name: ip-tables bridge? - zmienic na modul zamiast command
  # command: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
