---
#### Ansible Roles
- name: Install Ansible roles
  command: ansible-galaxy collection install "{{ item }}"
  loop: "{{ roles_to_install }}"
  when: roles_to_install is defined

- name: Copy repository configuration files
  copy: 
    src: "{{ repo_files_source }}/{{ item }}.repo"
    dest: "/etc/yum.repos.d/{{ item }}.repo"
  loop: "{{ repos_to_enable }}"

#### PACKAGES ####
- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    allowerasing: true
  loop: "{{ required_packages }}"
  when: "required_packages is defined"

#### SERVICES ####
- name: Enable required services now and on boot
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  loop: "{{ required_services }}"
  when: "required_services is defined"
