---
### TODO - dodac notify, firewall powinien byc przeladowany po dodaniu czegos do uslugi
- name: Firewalld - Przeladowanie uslugi
  ansible.posix.firewalld:
    state: reloaded
  listen: "reload firewall"