---
ansible_connection: ssh
ansible_user: ans_mariusz 
ansible_ssh_pass: mypassword 
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

repo_files_source: "/mnt/meta/repo_files"

local_nfs_ro_mount_paths: "{{ nfs_ro_export_dirs }}"
local_nfs_rw_mount_paths: "{{ nfs_rw_export_dirs }}"

### Main 
main_user: ans_mariusz
control_plane_ip: 192.168.1.10
main_machine_hostname: "control-plane"

#### NFS #### 
# CONTROL-PLANE Global settings!
nfs_ro_export_dirs: 
  - "/mnt/repos"
  - "/mnt/meta"
  - "/mnt/ansible"

nfs_rw_export_dirs:
  - "/exports/{{ main_machine_hostname }}"

# Paths exported by the nfs server  
nfs_export_paths: "{{ nfs_ro_export_dirs + nfs_rw_export_dirs }}"

# Destination paths for the nfs clients
local_nfs_mount_paths: "{{ nfs_ro_export_dirs + nfs_rw_export_dirs }}"