---
### Local iso mounts ###
local_iso_mounts: 
  - repos_mount_point: "/mnt/repos"
  - meta_mount_point: "/mnt/meta"
  - ansible_mount_point: "/mnt/ansible"

## Path /dev/sr0 is always the same because of the cloud-init
local_iso_device_paths: 
  - repos_device_path: "/dev/sr0"
  - meta_mount_point: "/dev/sr1"
  - ansible_mount_point: "/dev/sr2"

### NFS
nfs_export_dirs: 
  - nfs_repos_export_directory: "{{ repos_mount_point }}"
  - nfs_meta_export_directory: "{{ meta_mount_point }}"

nfs_export_options: "*(rw,sync,no_root_squash,no_all_squash)"

# Repos to be enabled 
repos_to_enable: 
  - AppStream
  - BaseOS
  - Kubernetes
  - docker-ce

roles_to_install:
  - 'community.general'
  - 'ansible.posix'

# Required packages 
required_packages:
  - "python3.11"
  - "kubectl"
  - "kubelet"
  - "kubeadm"
  - "docker-ce"
  - "bash-completion"
  - "containerd.io"

# Services required to be enabled on boot
required_services:
  - "kubelet"
