---
- name: Install NFS client package
  package:
    name: nfs-utils
    state: present

- name: Ensure NFS mount point exists
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ local_nfs_mount_paths }}"
  # when: "nfs_repos_mount_point is not mount"

- name: Mount NFS share
  ansible.posix.mount:
    path: "{{ item.0 }}"
    src: "{{ nfs_server }}:{{ item.1 }}"
    fstype: nfs
    opts: "rw,soft,intr"
    state: mounted
  with_together: 
    - "{{ local_nfs_mount_paths }}"
    - "{{ nfs_export_paths }}"

- name: Add entry to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ nfs_server }}:{{ item.0 }} {{ item.1 }} nfs {{ local_nfs_mount_options }} 0 0"
    create: yes
  with_together:
    - "{{ nfs_export_paths }}"
    - "{{ local_nfs_mount_paths }}"