version: '3'

services:

  whoami:
    image: containous/whoami
    ports:
     - "81:80"
    deploy:
        labels:
          - traefik.enable=true
          - traefik.http.routers.whoami2.rule=Host(`192.168.1.10`) && Path(`/whoami2`)
          - traefik.http.routers.whoami2.entryPoints=web
          - traefik.http.routers.whoami2.service=whoami2-service
          - traefik.http.services.whoami2-service.loadbalancer.server.port=80
          - traefik.docker.network=traefik-public

