version: "3.8"
services:
  prometheus:
    image: grafana/prometheus
    command:
      - "--web.listen-address=0.0.0.0:9090"
      - "--web.enable-admin-api"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - ingress  # Removed "prometheus_" prefix due to inconsistency
volumes:
  prometheus_data:

