--- 
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes

### DOCKER SWARM INIT ###
- name: Docker Swarm - Check if node is part of Swarm
  shell: "docker info | grep -v 'inactive' | grep '^.*Swarm.*active'"
  ignore_errors: true
  register: swarm_check_result

- name: Docker Swarm - Initialization
  command: "docker swarm init"
  when: swarm_check_result.stdout is not search('active') 
  register: swarm_init_result

- name: Docker Swarm - Node is already part of the cluster
  debug:
    msg: "Machine is already a member of the cluster"
  when: swarm_check_result.stdout is search('active') 
###

### SWARM - Get the join token ###
- name: Docker Swarm - Pobranie komendy pozwalajacej na dolaczenie do clustra 
  command: 
    cmd: "docker swarm join-token worker -q"
  register: tmp_swarm_join_token_worker  

- name: Docker Swarm - Zapisanie tokena do pliku tekstowego 
  copy: 
    content: "{{ tmp_swarm_join_token_worker.stdout }}"
    dest: "/exports/control-plane/token.txt"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: 0640
