---
- name: Ensure mount point exists
  file:
    path: "{{ repos_mount_point }}"
    state: directory
    mode: '0755'

vars:
  ihopefalse: "{{ '/etc/hosts' is mount }}"
  normallytrue: "{{ '/tmp' is mount }}"

- name: ihopefalse 
  debug: 
    var: ihopefalse

- name: normallytrue
  debug: 
    var: normallytrue

- name: Mount the optical drive
  mount:
    path: "{{ repos_mount_point }}"
    src: "{{ repos_device_path }}"
    fstype: iso9660
    opts: "ro"
    state: mounted
    boot: true
  when: not "{{ repos_mount_point is mount }}" 
