--- 
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes

- name: Docker Swarm - Inicjalizacja
  community.docker.docker_swarm:
    state: present
  register: swarm_init

- name: Debug swarm_init
  debug: 
    msg: "{{ swarm_init }}"

- name: Docker Swarm - Pobranie komendy pozwalajacej na dolaczenie do clustra 
  command: 
    cmd: "docker swarm join-token worker -q"
  register: tmp_swarm_join_token_worker  

- name: Docker Swarm - Zapisanie tokena do pliku tekstowego 
  copy: 
    content: "tmp_swarm_join_token_worker"
    dest: "/exports/control-plane/token.txt"
    mode: 0640