--- 

- name: Ensure mount point exists
  file:
    path: "{{ repos_mount_point }}"
    state: directory
    mode: '0755'
  when: "repos_mount_point is not mount"

- name: Mount the optical drive
  mount:
    path: "{{ repos_mount_point }}"
    src: "{{ repos_device_path }}"
    fstype: iso9660
    opts: "ro"
    state: mounted
    boot: true
  when: "repos_mount_point is not mount"


- name: Copy AppStream repository file 
  copy: 
    src: files/AppStream.repo
    dest: /etc/yum.repos.d/AppStream.repo
  

- name: Copy AppStream repository file 
  copy: 
    src: files/BaseOS.repo
    dest: /etc/yum.repos.d/BaseOS.repo