--- 
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes


- name: Docker Swarm - Check if node is part of Swarm
  command: "docker info  | grep -w '^.*Swarm.*active'"
  rescue:
    - name: Docker Swarm - Inicjalizacja
      cmd: "docker swarm init"
    - name: Docker Swarm - Jest juz członkiem clustra
      debug: 
        msg: Maszyna jest czlonkiem clustra

- name: Docker Swarm - Pobranie komendy pozwalajacej na dolaczenie do clustra 
  command: 
    cmd: "docker swarm join-token worker -q"
  register: tmp_swarm_join_token_worker  

- name: Docker Swarm - Zapisanie tokena do pliku tekstowego 
  copy: 
    content: "tmp_swarm_join_token_worker"
    dest: "/exports/control-plane/token.txt"
    mode: 0640