---
# tasks file for host
- name: Ensure mount point exists
  file:
    path: "{{ repos_mount_point }}"
    state: directory
  when: "repos_mount_point is not defined"  # Fix the condition

- name: Mount the optical drive
  mount:
    path: "{{ repos_mount_point }}"
    src: "{{ repos_device_path }}"
    fstype: iso9660
    opts: "ro"
    state: mounted
    boot: true
  when: "repos_mount_point is not defined"  # Fix the condition