---
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes

# - name: Rozwiazanie problemu enable bridge-nf-call-iptables
  # command: "{{ item }}"
  # with_items: 
  # - "modprobe br_netfilter"
  # - "sysctl -w net.bridge.bridge-nf-call-iptables=1"
  # - "echo \"net.bridge.bridge-nf-call-iptables = 1\" | tee /etc/sysctl.d/99-kubernetes-cri.conf"
  # - "sysctl --system"

# - name: Rozwiazanie problemu ERROR FileContent--proc-sys-net-ipv4-ip_forward
  # command: "{{ item }}"
  # with_items: 
  # - "sysctl -w net.ipv4.ip_forward=1"
  # - "echo 'net.ipv4.ip_forward = 1' | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf"
  # - "sudo sysctl --system"


- name: Docker Swarm - Wczytaj token do zmiennej
  ansible.builtin.slurp:
    src: "/exports/control-plane/token.txt"
  register: swarm_join_token_worker

- name: Docker Swarm - Join cluster 
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ control_plane_ip }}:2377"
    join_token: "{{ swarm_join_token_worker }}"
  register: join_result

- debug:
    msg: "Worker joined swarm with code: {{ join_result.rc }}"