---
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes

- name: Docker Swarm - Wczytaj token do zmiennej
  ansible.builtin.slurp:
    src: "/exports/control-plane/token.txt"
  register: swarm_join_token_worker

- name: Docker Swarm - Join cluster 
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ control_plane_ip }}:2377"
    join_token: "{{ swarm_join_token_worker }}"
  register: join_result

- debug:
    msg: "Worker joined swarm with code: {{ join_result.rc }}"