---
# - name: Zmiana w configu containerd
  # command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

# - name: Wlaczenie uslugi containerd przy starcie systemu
  # service: 
    # name: containerd
    # enabled: yes

### DOCKER SWARM JOIN ###
- name: Docker Swarm - Check if node is part of Swarm
  shell: "docker info | grep -v 'inactive' | grep '^.*Swarm.*active'"
  register: swarm_check_result
  ignore_errors: true

- name: Docker Swarm - Initialization
  command: "docker swarm join --token {{ lookup('ansible.builtin.file','/exports/control-plane/token.txt') }} {{ control_plane_ip }}:2377"
  register: swarm_init_result
  when: swarm_check_result is not defined or swarm_check_result.rc != 0
