---
- name: Zmiana w configu containerd
  command: sed -i 's/disabled_plugins/\# disabled_plugins/g' /etc/containerd/config.toml

- name: Restart uslugi containerd 
  service: 
    name: containerd
    state: restarted
    
- name: Wlaczenie uslugi containerd przy starcie systemu
  service: 
    name: containerd
    enabled: yes

- name: Docker Swarm - Wczytaj token do zmiennej
  ansible.builtin.slurp:
    src: "/exports/control-plane/token.txt"
  register: swarm_join_token_worker

### DOCKER SWARM JOIN ###
- name: Docker Swarm - Check if node is part of Swarm
  shell: "docker info | grep -v 'inactive' | grep '^.*Swarm.*active'"
  ignore_errors: true
  register: swarm_check_result

- name: Docker Swarm - Initialization
  command: "docker swarm join --advertise-addr {{ control_plane_ip }}:2377 --token {{ tmp_swarm_join_token_worker.stdout_lines }}"
  register: swarm_init_result
  when: swarm_check_result.rc != 0


- name: Docker Swarm - Node is already part of the cluster
  debug:
    msg: "Machine is already a member of the cluster"
  when: swarm_check_result.rc = 0
###

