---
- name: Mounts - Ensure mount point exists
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ local_iso_mounts }}"

- name: Mounts - Mount the optical drives
  mount:
    path: "{{ item.0 }}"
    src: "{{ item.1 }}"
    fstype: iso9660
    opts: "ro"
    state: mounted
    boot: true
  with_together:
    - "{{ local_iso_mounts }}"
    - "{{ local_iso_device_paths }}"

- name: NFS - Install server package
  package:
    name: nfs-utils
    state: present

- name: NFS - Start and enable
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: NFS - Ensure writable paths exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop: "{{ nfs_rw_export_dirs }}"

- name: Add NFS export entry to /etc/exports
  lineinfile:
    path: /etc/exports
    line: "{{ item }} {{ nfs_export_options }}"
    create: yes
  loop: "{{ nfs_export_paths }}"
  notify: "nfs service restart"