---
- name: Ensure mount point exists
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ local_iso_mounts }}"

- name: Mount the optical drive
  mount:
    path: "{{ item.0 }}"
    src: "{{ item.1 }}"
    fstype: iso9660
    opts: "ro"
    state: mounted
    boot: true
  with_together:
    - "{{ local_iso_mounts }}"
    - "{{ local_iso_device_paths }}"

- name: Install NFS server package
  package:
    name: nfs-utils
    state: present

- name: Ensure NFS service is enabled and running
  service:
    name: nfs-server
    state: started
    enabled: yes

- name: Add NFS export entry to /etc/exports
  lineinfile:
    path: /etc/exports
    line: "{{ item }} {{ nfs_export_options }}"
    create: yes
  loop: "{{ nfs_export_dirs }}"

- name: Reload NFS server configuration
  command: exportfs -ra



