---
- name: "Initialize MongoDB Replica Set"
  command: "mongosh 192.168.1.10:27017 --eval 'rs.initiate(
    {
      _id: \"replicaTest\",
      members: [
        { _id: 0, host : \"192.168.1.10:27017\" },
        { _id: 1, host : \"192.168.1.201:27018\" },
        { _id: 2, host : \"192.168.1.202:27019\" }
      ]
    })'"
  run_once: true

- name: Create database
  command: > 
    mongosh mydatabase --eval '
    db.createCollection("mycollection");
    db.mycollection.insertMany([
      { name: "Alice", age: 30 },
      { name: "Bob", age: 25 },
      { name: "Charlie", age: 35 }
    ]);
    '
  run_once: true

- name: Verify database creation
  command: >
    mongosh mydatabase --eval '
    db.getCollectionNames();
    '
  register: result

- name: Debug database collections
  debug:
    var: result.stdout
