---

- name: Check if MongoDB replica set is configured
  command: "mongosh --host 192.168.1.10:27017 --quiet --eval 'rs.status().ok'"
  register: replica_set_check
  ignore_errors: yes

- name: Debug Replica Set Check Result
  debug:
    msg: "Replica set check result: {{ replica_set_check.stdout }}"

- name: "Initialize MongoDB Replica Set"
  command: "mongosh --host 192.168.1.10:27017 --eval 'rs.initiate(
    {
      _id: \"replicaTest\",
      members: [
        { _id: 0, host : \"192.168.1.10:27017\" },
        { _id: 1, host : \"192.168.1.201:27018\" },
        { _id: 2, host : \"192.168.1.202:27019\" }
      ]
    })'"
  run_once: true
  when: replica_set_check.stdout != "1"

- name: Run mongosh to get replica set state
  command: mongosh --quiet --eval 'rs.status()'
  register: mongo_rs_status
  ignore_errors: yes
  when: replica_set_check.stdout == "1"

- name: Extract syncingTo value using shell command
  shell: "echo '{{ mongo_rs_status.stdout }}' | grep 'syncingTo:' | awk -F'syncingTo: ' '{print $2}' | cut -d \"'\" -f 1 | sed s/,//g |  head -n 1"
  register: primary_name

- name: Debug primary name
  debug:
    msg: "Primary name: {{ primary_name }}"

- name: Create database
  command: > 
    mongosh --host "{{ primary_name }}" mydatabase --eval '
    db.createCollection("mycollection");
    db.mycollection.insertMany([
      { name: "Alice", age: 30 },
      { name: "Bob", age: 25 },
      { name: "Charlie", age: 35 }
    ]);
    '
  run_once: true

- name: Verify database creation
  command: >
    mongosh mydatabase --eval '
    db.getCollectionNames();
    '
  register: result

- name: Debug database collections
  debug:
    var: result.stdout
