---
- name: "Set up '{{ main_machine }}' host" 
  hosts: grp_control_plane
  remote_user: "{{ main_user }}"
  become: yes
  
  roles:
#    - common
#    - nfs_server 
#    - control_plane

- name: Set up node machines
  hosts: grp_nodes
  remote_user: "{{ main_user }}" 
  become: yes

  roles:
#    - nfs_client
#    - common
#    - node

- name: "Reboot" 
  hosts: grp_nodes
  remote_user: "{{ main_user }}"
  become: yes

  tasks: 
    - name: Reboot
      reboot:
        reboot_timeout: 300
        test_command: uptime

- name: "Set up docker swarm service"
  hosts: grp_control_plane
  remote_user: "{{ main_user }}"
  become: yes

  roles:
    - mongo_swarm      

  tasks: 
    - name: Scale mongo
      command: "docker service scale mongo_control-plane=0"

    - name: Scale mongo
      command: "docker service scale mongo_control-plane=1"

- name: "Set up docker swarm replica set"
  hosts: 192.168.1.201
  remote_user: "{{ main_user }}"
  become: no

  roles:
    - mongo_replica_set

